import Foundation
import AppKit

/// Executes automated tasks on macOS using native `NSAppleScript`.
/// This avoids the overhead of spawning shell processes via `/usr/bin/osascript`.
public final class WorkflowHandler {
    
    public init() {}
    
    /// Executes a system command based on the route parameters.
    ///
    /// - Parameters:
    ///   - action: The string identifier of the action to execute (e.g., "open_app", "send_email").
    ///   - parameters: A dictionary containing the required arguments for the specific action payload.
    public func executeCommand(action: String, parameters: [String: String]) {
        AppLog.info("Preparing to execute workflow for action: \(action)", category: .routing)
        
        switch action {
        case "open_app":
            if let appName = parameters["app_name"] {
                openApp(name: appName)
            } else {
                AppLog.error("Missing 'app_name' parameter for open_app action", category: .routing)
            }
            
        case "send_email":
            let recipient = parameters["recipient"] ?? ""
            let body = parameters["body"] ?? ""
            AppLog.info("Would draft email to: \(recipient)", category: .routing)
            executeAppleScript(source: emailScript(to: recipient, body: body))
            
        case "paste_text":
            // This would normally be handled by TextInjector, but keeping as fallback
            let text = parameters["text"] ?? ""
            executeAppleScript(source: pasteScript(text: text))
            
        default:
            AppLog.warning("Unknown command action: \(action)", category: .routing)
        }
    }
    
    // MARK: - Dedicated Workflows
    
    /// Generates and executes an AppleScript to bring a specific application to the foreground.
    /// - Parameter name: The name of the macOS application.
    private func openApp(name: String) {
        let safeName = name.replacingOccurrences(of: "\"", with: "")
                           .replacingOccurrences(of: "\\", with: "")
        let source = "tell application \"\(safeName)\"\nactivate\nend tell"
        executeAppleScript(source: source)
    }
    
    /// Constructs an AppleScript payload to draft a new email in the Mail app.
    /// - Parameters:
    ///   - recipient: The destination email address.
    ///   - body: The generated text body for the email.
    /// - Returns: A raw AppleScript string.
    private func emailScript(to recipient: String, body: String) -> String {
        return """
        tell application "Mail"
            set newMessage to make new outgoing message with properties {subject:"Generated by EchoFlow", content:"\(body)", visible:true}
            tell newMessage
                make new to recipient at end of to recipients with properties {address:"\(recipient)"}
            end tell
            activate
        end tell
        """
    }
    
    /// Constructs an AppleScript payload to set the clipboard and simulate Cmd+V using System Events.
    /// - Parameter text: The text to paste.
    /// - Returns: A raw AppleScript string.
    private func pasteScript(text: String) -> String {
        return """
        set the clipboard to "\(text)"
        tell application "System Events"
            keystroke "v" using command down
        end tell
        """
    }
    
    // MARK: - Native Execution Engine
    
    /// Compiles and executes the provided AppleScript string natively on a background thread.
    private func executeAppleScript(source: String) {
        // Since NSAppleScript often interacts with System Events or app UIs
        guard AXIsProcessTrusted() else {
            AppLog.error("Missing Accessibility Privileges. Cannot execute AppleScript.", category: .routing)
            return
        }
        
        Task.detached {
            var errorInfo: NSDictionary?
            if let scriptObject = NSAppleScript(source: source) {
                scriptObject.executeAndReturnError(&errorInfo)
                
                if let error = errorInfo {
                    AppLog.error("NSAppleScript execution failed: \(error)", category: .routing)
                } else {
                    AppLog.info("Successfully executed AppleScript.", category: .routing)
                }
            } else {
                AppLog.error("Failed to compile AppleScript source.", category: .routing)
            }
        }
    }
}

