import Foundation

/// Executes automated tasks on macOS using osascript (AppleScript/JXA).
public final class WorkflowHandler {
    
    public init() {}
    
    /// Executes a system command based on the route parameters.
    public func executeCommand(action: String, parameters: [String: String]) async throws {
        switch action {
        case "send_email":
            let recipient = parameters["recipient"] ?? ""
            let body = parameters["body"] ?? ""
            try await invokeAppleScript(template: emailScript(to: recipient, body: body))
            
        case "paste_text":
            let text = parameters["text"] ?? ""
            try await invokeAppleScript(template: pasteScript(text: text))
            
        default:
            print("Unknown action: \(action)")
        }
    }
    
    /// Runs AppleScript via the /usr/bin/osascript command line wrapper.
    private func invokeAppleScript(template: String) async throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
        
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        
        // Feed the script to standard input
        process.arguments = ["-e", template]
        
        try process.run()
        process.waitUntilExit()
    }
    
    private func emailScript(to recipient: String, body: String) -> String {
        return """
        tell application "Mail"
            set newMessage to make new outgoing message with properties {subject:"Generated by EchoFlow", content:"\(body)", visible:true}
            tell newMessage
                make new to recipient at end of to recipients with properties {address:"\(recipient)"}
            end tell
            activate
        end tell
        """
    }
    
    private func pasteScript(text: String) -> String {
        return """
        set the clipboard to "\(text)"
        tell application "System Events"
            keystroke "v" using command down
        end tell
        """
    }
}
